---
platform: vmware_player

vcenter:
  hostname: 192.168.0.101
  port: 443
  username: administrator@vsphere.local
  password: P@ssw0rd123
  datacenter_name: DataCenter
  cluster_name: cluster01

esxi:
  hostnames:
    - 192.168.0.111
    - 192.168.0.112
    - 192.168.0.113
  username: root
  password: P@ssw0rd123
  vmkernel_port: vmk0
