---
platform: vmware_player

vcenter:
  hostname: 192.168.0.101
  port: 443
  username: administrator@vsphere.local
  password: P@ssword123
  datacenter_name: DataCenter
  cluster_name: cluster01
  folder:
    vm: dev
    backup: backup
  license: 00000-00000-00000-00000-00000

esxi:
  hostnames:
    - 192.168.0.111
    - 192.168.0.112
    - 192.168.0.113
  username: root
  password: P@ssword123
  vmkernel_port: vmk0
  license: 00000-00000-00000-00000-00000

vm_templates:
  - name: OpenShift4_rhcos-4.4.3
    ovf: /home/nbchk/work/vsphere/ansible-vsphere-poc/repository/ova/rhcos-4.4.3-x86_64-vmware.x86_64.ova
    sha256: 832b1f07f12608a7501ef944e6aa0021a76f2f26703a435d4d3628f1667dde15
    datastore: datastore1
    networks:
      VM Network: VM Network
  - name: Manage-1.0.0
    ovf: /home/nbchk/work/vsphere/ansible-vsphere-poc/repository/ova/rhcos-4.4.3-x86_64-vmware.x86_64.ova
    sha256: 832b1f07f12608a7501ef944e6aa0021a76f2f26703a435d4d3628f1667dde15
    datastore: datastore1 (1)
    networks:
      VM Network: VM Network
  - name: LoadBlancer-1.0.0
    ovf: /home/nbchk/work/vsphere/ansible-vsphere-poc/repository/ova/rhcos-4.4.3-x86_64-vmware.x86_64.ova
    sha256: 832b1f07f12608a7501ef944e6aa0021a76f2f26703a435d4d3628f1667dde15
    datastore: datastore1 (2)
    networks:
      VM Network: VM Network

bootstrap:
  common_specs:
    # ignition: 'master.64'
    template: OpenShift4_rhcos-4.4.3
    hardware:
      num_cpus: 1
      num_cpu_cores_per_socket: 1
      cpu_reservation: 100
      memory_mb: 512
      mem_reservation: 512
      memory_reservation_lock: true
  vms:
    - name: bootstrap001
      esxi_hostname: 192.168.0.111
      disk:
        - size_gb: 16
          type: thin
          datastore: datastore1
      networks:
        - name: VM Network
          type: static
          mac: 00:50:56:a8:aa:a1
          # vlan:

master:
  common_specs:
    # ignition: 'master.64'
    template: OpenShift4_rhcos-4.4.3
    hardware:
      num_cpus: 1
      num_cpu_cores_per_socket: 1
      cpu_reservation: 100
      memory_mb: 512
      mem_reservation: 512
      memory_reservation_lock: true
  vms:
    - name: master001
      esxi_hostname: 192.168.0.111
      disk:
        - size_gb: 16
          type: thin
          datastore: datastore1
      networks:
        - name: VM Network
          type: static
          mac: 00:50:56:a8:aa:b1
          # vlan:
    - name: master002
      esxi_hostname: 192.168.0.112
      disk:
        - size_gb: 16
          type: thin
          datastore: datastore1 (1)
      networks:
        - name: VM Network
          type: static
          mac: 00:50:56:a8:aa:b2
          # vlan:
    - name: master003
      esxi_hostname: 192.168.0.113
      disk:
        - size_gb: 16
          type: thin
          datastore: datastore1 (2)
      networks:
        - name: VM Network
          type: static
          mac: 00:50:56:a8:aa:b3
          # vlan:

infra:
  common_specs:
    # ignition: 'master.64'
    template: OpenShift4_rhcos-4.4.3
    hardware:
      num_cpus: 1
      num_cpu_cores_per_socket: 1
      cpu_reservation: 100
      memory_mb: 512
      mem_reservation: 512
      memory_reservation_lock: true
  vms:
    - name: infra001
      esxi_hostname: 192.168.0.111
      disk:
        - size_gb: 16
          type: thin
          datastore: datastore1
      networks:
        - name: VM Network
          type: static
          mac: 00:50:56:a8:aa:c1
          # vlan:
    - name: infra002
      esxi_hostname: 192.168.0.112
      disk:
        - size_gb: 16
          type: thin
          datastore: datastore1 (1)
      networks:
        - name: VM Network
          type: static
          mac: 00:50:56:a8:aa:c2
          # vlan:
    - name: infra003
      esxi_hostname: 192.168.0.113
      disk:
        - size_gb: 16
          type: thin
          datastore: datastore1 (2)
      networks:
        - name: VM Network
          type: static
          mac: 00:50:56:a8:aa:c3
          # vlan:

worker:
  common_specs:
    # ignition: 'master.64'
    template: OpenShift4_rhcos-4.4.3
    hardware:
      num_cpus: 1
      num_cpu_cores_per_socket: 1
      cpu_reservation: 100
      memory_mb: 512
      mem_reservation: 512
      memory_reservation_lock: true
  vms:
    - name: worker001
      esxi_hostname: 192.168.0.112
      disk:
        - size_gb: 16
          type: thin
          datastore: datastore1 (1)
      networks:
        - name: VM Network
          type: static
          mac: 00:50:56:a8:aa:d1
          # vlan:
    - name: worker002
      esxi_hostname: 192.168.0.113
      disk:
        - size_gb: 16
          type: thin
          datastore: datastore1 (2)
      networks:
        - name: VM Network
          type: static
          mac: 00:50:56:a8:aa:d2
          # vlan:

manage:
  common_specs:
    template: Manage-1.0.0
    hardware:
      num_cpus: 1
      num_cpu_cores_per_socket: 1
      cpu_reservation: 100
      memory_mb: 512
      mem_reservation: 512
      memory_reservation_lock: true
  vms:
    - name: manage001
      esxi_hostname: 192.168.0.111
      disk:
        - size_gb: 16
          type: thin
          datastore: datastore1
        - size_gb: 16
          type: thin
          datastore: datastore1
      networks:
        - name: VM Network
          type: static
          mac: 00:50:56:a8:aa:e1
          # vlan:

loadbalancer:
  common_specs:
    template: LoadBlancer-1.0.0
    hardware:
      num_cpus: 1
      num_cpu_cores_per_socket: 1
      cpu_reservation: 100
      memory_mb: 512
      mem_reservation: 512
      memory_reservation_lock: true
  vms:
    - name: loadbalancer001
      esxi_hostname: 192.168.0.111
      disk:
        - size_gb: 16
          type: thin
          datastore: datastore1
      networks:
        - name: VM Network
          type: static
          mac: 00:50:56:a8:aa:f1
          # vlan:
