---
- name: Add the license to the vcenter
  community.vmware.vcenter_license:
    hostname: "{{ vcenter.hostname }}"
    port: "{{ vcenter.port }}"
    username: "{{ vcenter.username }}"
    password: "{{ vcenter.password }}"
    license: "{{ vcenter.license }}"
    validate_certs: false
    state: present
  changed_when: false

- name: Add licenses to esxi hosts
  community.vmware.vcenter_license:
    hostname: "{{ vcenter.hostname }}"
    port: "{{ vcenter.port }}"
    username: "{{ vcenter.username }}"
    password: "{{ vcenter.password }}"
    esxi_hostname: "{{ esxi_hostname }}"
    license: "{{ esxi.license }}"
    validate_certs: false
    state: present
  changed_when: false
  loop: "{{ esxi.hostnames }}"
  loop_control:
    loop_var: esxi_hostname
