---
- name: Create the datacenter in the vcenter
  vmware_datacenter:
    hostname: "{{ vcenter.hostname }}"
    port: "{{ vcenter.port }}"
    username: "{{ vcenter.username }}"
    password: "{{ vcenter.password }}"
    datacenter_name: "{{ vcenter.datacenter_name }}"
    validate_certs: no
    state: present
