---
- name: Create the list of folder names
  ansible.builtin.set_fact:
    folder_names: "{{ vcenter.folder | dict2items | map(attribute='value') | list }}"

- name: Create the vm folders in the datacenter
  community.vmware.vcenter_folder:
    hostname: "{{ vcenter.hostname }}"
    port: "{{ vcenter.port }}"
    username: "{{ vcenter.username }}"
    password: "{{ vcenter.password }}"
    datacenter_name: "{{ vcenter.datacenter_name }}"
    folder_name: "{{ folder_name }}"
    folder_type: vm
    validate_certs: false
    state: present
  loop: "{{ folder_names }}"
  loop_control:
    loop_var: folder_name
