---
- name: Deploy bootstrap vms from vm template
  community.vmware.vmware_guest:
    hostname: "{{ vcenter.hostname }}"
    port: "{{ vcenter.port }}"
    username: "{{ vcenter.username }}"
    password: "{{ vcenter.password }}"
    datacenter: "{{ vcenter.datacenter_name }}"
    folder: "/{{ vcenter.datacenter_name }}/vm/{{ vcenter.folder.vm }}"
    name: "{{ vm.name }}"
    template: "{{ bootstrap.common_specs.template }}"
    esxi_hostname: "{{ vm.esxi_hostname }}"
    hardware: "{{ bootstrap.common_specs.hardware }}"
    disk: "{{ vm.disk }}"
    networks: "{{ vm.networks }}"
    validate_certs: false
    state: poweredoff
  loop: "{{ bootstrap.vms }}"
  loop_control:
    loop_var: vm

- name: Deploy master vms from vm template
  community.vmware.vmware_guest:
    hostname: "{{ vcenter.hostname }}"
    port: "{{ vcenter.port }}"
    username: "{{ vcenter.username }}"
    password: "{{ vcenter.password }}"
    datacenter: "{{ vcenter.datacenter_name }}"
    folder: "/{{ vcenter.datacenter_name }}/vm/{{ vcenter.folder.vm }}"
    name: "{{ vm.name }}"
    template: "{{ master.common_specs.template }}"
    esxi_hostname: "{{ vm.esxi_hostname }}"
    hardware: "{{ master.common_specs.hardware }}"
    disk: "{{ vm.disk }}"
    networks: "{{ vm.networks }}"
    validate_certs: false
    state: poweredoff
  loop: "{{ master.vms }}"
  loop_control:
    loop_var: vm

- name: Deploy infra vms from vm template
  community.vmware.vmware_guest:
    hostname: "{{ vcenter.hostname }}"
    port: "{{ vcenter.port }}"
    username: "{{ vcenter.username }}"
    password: "{{ vcenter.password }}"
    datacenter: "{{ vcenter.datacenter_name }}"
    folder: "/{{ vcenter.datacenter_name }}/vm/{{ vcenter.folder.vm }}"
    name: "{{ vm.name }}"
    template: "{{ infra.common_specs.template }}"
    esxi_hostname: "{{ vm.esxi_hostname }}"
    hardware: "{{ infra.common_specs.hardware }}"
    disk: "{{ vm.disk }}"
    networks: "{{ vm.networks }}"
    validate_certs: false
    state: poweredoff
  loop: "{{ infra.vms }}"
  loop_control:
    loop_var: vm

- name: Deploy worker vms from vm template
  community.vmware.vmware_guest:
    hostname: "{{ vcenter.hostname }}"
    port: "{{ vcenter.port }}"
    username: "{{ vcenter.username }}"
    password: "{{ vcenter.password }}"
    datacenter: "{{ vcenter.datacenter_name }}"
    folder: "/{{ vcenter.datacenter_name }}/vm/{{ vcenter.folder.vm }}"
    name: "{{ vm.name }}"
    template: "{{ worker.common_specs.template }}"
    esxi_hostname: "{{ vm.esxi_hostname }}"
    hardware: "{{ worker.common_specs.hardware }}"
    disk: "{{ vm.disk }}"
    networks: "{{ vm.networks }}"
    validate_certs: false
    state: poweredoff
  loop: "{{ worker.vms }}"
  loop_control:
    loop_var: vm

- name: Deploy manage vms from vm template
  community.vmware.vmware_guest:
    hostname: "{{ vcenter.hostname }}"
    port: "{{ vcenter.port }}"
    username: "{{ vcenter.username }}"
    password: "{{ vcenter.password }}"
    datacenter: "{{ vcenter.datacenter_name }}"
    folder: "/{{ vcenter.datacenter_name }}/vm/{{ vcenter.folder.vm }}"
    name: "{{ vm.name }}"
    template: "{{ manage.common_specs.template }}"
    esxi_hostname: "{{ vm.esxi_hostname }}"
    hardware: "{{ manage.common_specs.hardware }}"
    disk: "{{ vm.disk }}"
    networks: "{{ vm.networks }}"
    validate_certs: false
    state: poweredoff
  loop: "{{ manage.vms }}"
  loop_control:
    loop_var: vm

- name: Deploy loadbalancer vms from vm template
  community.vmware.vmware_guest:
    hostname: "{{ vcenter.hostname }}"
    port: "{{ vcenter.port }}"
    username: "{{ vcenter.username }}"
    password: "{{ vcenter.password }}"
    datacenter: "{{ vcenter.datacenter_name }}"
    folder: "/{{ vcenter.datacenter_name }}/vm/{{ vcenter.folder.vm }}"
    name: "{{ vm.name }}"
    template: "{{ loadbalancer.common_specs.template }}"
    esxi_hostname: "{{ vm.esxi_hostname }}"
    hardware: "{{ loadbalancer.common_specs.hardware }}"
    disk: "{{ vm.disk }}"
    networks: "{{ vm.networks }}"
    validate_certs: false
    state: poweredoff
  loop: "{{ loadbalancer.vms }}"
  loop_control:
    loop_var: vm
