---
- name: Deploy bootstrap vms from vm template
  vmware_guest:
    hostname: "{{ vcenter.hostname }}"
    port: "{{ vcenter.port }}"
    username: "{{ vcenter.username }}"
    password: "{{ vcenter.password }}"
    datacenter: "{{ vcenter.datacenter_name }}"
    folder: "/{{ vcenter.datacenter_name }}/vm/{{ vcenter.folder_name }}"
    name: "{{ vm.name }}"
    template: "{{ bootstrap_vm.common_specs.template }}"
    esxi_hostname: "{{ vm.esxi_hostname }}"
    hardware: "{{ bootstrap_vm.common_specs.hardware }}"
    disk: "{{ vm.disk }}"
    networks: "{{ vm.networks }}"
    validate_certs: no
    state: poweredoff
  loop: "{{ bootstrap_vm.vms }}"
  loop_control:
    loop_var: vm

- name: Deploy master vms from vm template
  vmware_guest:
    hostname: "{{ vcenter.hostname }}"
    port: "{{ vcenter.port }}"
    username: "{{ vcenter.username }}"
    password: "{{ vcenter.password }}"
    datacenter: "{{ vcenter.datacenter_name }}"
    folder: "/{{ vcenter.datacenter_name }}/vm/{{ vcenter.folder_name }}"
    name: "{{ vm.name }}"
    template: "{{ master_vm.common_specs.template }}"
    esxi_hostname: "{{ vm.esxi_hostname }}"
    hardware: "{{ master_vm.common_specs.hardware }}"
    disk: "{{ vm.disk }}"
    networks: "{{ vm.networks }}"
    validate_certs: no
    state: poweredoff
  loop: "{{ master_vm.vms }}"
  loop_control:
    loop_var: vm

- name: Deploy infra vms from vm template
  vmware_guest:
    hostname: "{{ vcenter.hostname }}"
    port: "{{ vcenter.port }}"
    username: "{{ vcenter.username }}"
    password: "{{ vcenter.password }}"
    datacenter: "{{ vcenter.datacenter_name }}"
    folder: "/{{ vcenter.datacenter_name }}/vm/{{ vcenter.folder_name }}"
    name: "{{ vm.name }}"
    template: "{{ infra_vm.common_specs.template }}"
    esxi_hostname: "{{ vm.esxi_hostname }}"
    hardware: "{{ infra_vm.common_specs.hardware }}"
    disk: "{{ vm.disk }}"
    networks: "{{ vm.networks }}"
    validate_certs: no
    state: poweredoff
  loop: "{{ infra_vm.vms }}"
  loop_control:
    loop_var: vm

- name: Deploy worker vms from vm template
  vmware_guest:
    hostname: "{{ vcenter.hostname }}"
    port: "{{ vcenter.port }}"
    username: "{{ vcenter.username }}"
    password: "{{ vcenter.password }}"
    datacenter: "{{ vcenter.datacenter_name }}"
    folder: "/{{ vcenter.datacenter_name }}/vm/{{ vcenter.folder_name }}"
    name: "{{ vm.name }}"
    template: "{{ worker_vm.common_specs.template }}"
    esxi_hostname: "{{ vm.esxi_hostname }}"
    hardware: "{{ worker_vm.common_specs.hardware }}"
    disk: "{{ vm.disk }}"
    networks: "{{ vm.networks }}"
    validate_certs: no
    state: poweredoff
  loop: "{{ worker_vm.vms }}"
  loop_control:
    loop_var: vm

- name: Deploy manage vms from vm template
  vmware_guest:
    hostname: "{{ vcenter.hostname }}"
    port: "{{ vcenter.port }}"
    username: "{{ vcenter.username }}"
    password: "{{ vcenter.password }}"
    datacenter: "{{ vcenter.datacenter_name }}"
    folder: "/{{ vcenter.datacenter_name }}/vm/{{ vcenter.folder_name }}"
    name: "{{ vm.name }}"
    template: "{{ manage_vm.common_specs.template }}"
    esxi_hostname: "{{ vm.esxi_hostname }}"
    hardware: "{{ manage_vm.common_specs.hardware }}"
    disk: "{{ vm.disk }}"
    networks: "{{ vm.networks }}"
    validate_certs: no
    state: poweredoff
  loop: "{{ manage_vm.vms }}"
  loop_control:
    loop_var: vm

- name: Deploy loadbalancer vms from vm template
  vmware_guest:
    hostname: "{{ vcenter.hostname }}"
    port: "{{ vcenter.port }}"
    username: "{{ vcenter.username }}"
    password: "{{ vcenter.password }}"
    datacenter: "{{ vcenter.datacenter_name }}"
    folder: "/{{ vcenter.datacenter_name }}/vm/{{ vcenter.folder_name }}"
    name: "{{ vm.name }}"
    template: "{{ loadbalancer_vm.common_specs.template }}"
    esxi_hostname: "{{ vm.esxi_hostname }}"
    hardware: "{{ loadbalancer_vm.common_specs.hardware }}"
    disk: "{{ vm.disk }}"
    networks: "{{ vm.networks }}"
    validate_certs: no
    state: poweredoff
  loop: "{{ loadbalancer_vm.vms }}"
  loop_control:
    loop_var: vm
