---
- name: Enable the vmotion feature on the vmkernel port on esxi hosts
  ansible.builtin.command: |
    govc host.vnic.service
      -host {{ esxi_hostname }}
      -enable=true vmotion {{ esxi.vmkernel_port }}
  environment:
    GOVC_URL: "{{ vcenter.hostname }}:{{ vcenter.port }}"
    GOVC_USERNAME: "{{ vcenter.username }}"
    GOVC_PASSWORD: "{{ vcenter.password }}"
    GOVC_INSECURE: "true"
  changed_when: false
  loop: "{{ esxi.hostnames }}"
  loop_control:
    loop_var: esxi_hostname
  when: platform != "vcsim"
# - name: Gather VMKernel info about ESXi Host
#   vmware_vmkernel_info:
#     hostname: "{{ vcenter.hostname }}"
#     port: "{{ vcenter.port }}"
#     username: "{{ vcenter.username }}"
#     password: "{{ vcenter.password }}"
#     esxi_hostname: 192.168.0.111
#     # esxi_hostname: "{{ esxi_hostname }}"
#     validate_certs: no
#   register: host_vmks

# - debug:
#     var: host_vmks

# -  name: Add Management vmkernel port using static network type
#    vmware_vmkernel:
#       hostname: "{{ vcenter.hostname }}"
#       port: "{{ vcenter.port }}"
#       username: "{{ vcenter.username }}"
#       password: "{{ vcenter.password }}"
#       esxi_hostname: 192.168.0.111
#       # esxi_hostname: "{{ esxi_hostname }}"
#       vswitch_name: vSwitch0
#       portgroup_name: Management Network
#       # network:
#       #   type: 'static'
#       #   ip_address: 192.168.127.10
#       #   subnet_mask: 255.255.255.0
#       validate_certs: no
#       state: present
#       enable_mgmt: True

# -  name: Add Management vmkernel port using DHCP network type
#    vmware_vmkernel:
#       hostname: '{{ esxi_hostname }}'
#       username: '{{ esxi_username }}'
#       password: '{{ esxi_password }}'
#       esxi_hostname: '{{ esxi_hostname }}'
#       vswitch_name: vSwitch0
#       portgroup_name: PG_0002
#       state: present
#       network:
#         type: 'dhcp'
#       enable_mgmt: True
#    delegate_to: localhost

# -  name: Change IP allocation from static to dhcp
#    vmware_vmkernel:
#       hostname: '{{ esxi_hostname }}'
#       username: '{{ esxi_username }}'
#       password: '{{ esxi_password }}'
#       esxi_hostname: '{{ esxi_hostname }}'
#       vswitch_name: vSwitch0
#       portgroup_name: PG_0002
#       state: present
#       device: vmk1
#       network:
#         type: 'dhcp'
#       enable_mgmt: True
#    delegate_to: localhost

# -  name: Delete VMkernel port
#    vmware_vmkernel:
#       hostname: '{{ esxi_hostname }}'
#       username: '{{ esxi_username }}'
#       password: '{{ esxi_password }}'
#       esxi_hostname: '{{ esxi_hostname }}'
#       vswitch_name: vSwitch0
#       portgroup_name: PG_0002
#       state: absent
#    delegate_to: localhost

# -  name: Add Management vmkernel port to Distributed Switch
#    vmware_vmkernel:
#       hostname: '{{ vcenter_hostname }}'
#       username: '{{ vcenter_username }}'
#       password: '{{ vcenter_password }}'
#       esxi_hostname: '{{ esxi_hostname }}'
#       dvswitch_name: dvSwitch1
#       portgroup_name: dvPG_0001
#       network:
#         type: 'static'
#         ip_address: 192.168.127.10
#         subnet_mask: 255.255.255.0
#       state: present
#       enable_mgmt: True
#    delegate_to: localhost

# -  name: Add vMotion vmkernel port with vMotion TCP/IP stack
#    vmware_vmkernel:
#       hostname: '{{ vcenter_hostname }}'
#       username: '{{ vcenter_username }}'
#       password: '{{ vcenter_password }}'
#       esxi_hostname: '{{ esxi_hostname }}'
#       dvswitch_name: dvSwitch1
#       portgroup_name: dvPG_0001
#       network:
#         type: 'static'
#         ip_address: 192.168.127.10
#         subnet_mask: 255.255.255.0
#         tcpip_stack: vmotion
#       state: present
#    delegate_to: localhost
