---
name: CI

on: [push, pull_request]

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv

      - name: Lock package version
        run: pipenv lock

      - name: Install packages
        run: pipenv sync --dev

      - name: Run ansible-lint
        run: pipenv run ansible-lint
